#define	MSG_ERROR_NULL_POINTER			"Null pointer"
#define	MSG_ERROR_INVALID_ARG			"Invalid argument"
#define	MSG_ERROR_INVALID_ARGS_NUMBER		"Invalid number of arguments"
#define	MSG_ERROR_INVALID_OUTPUT_FORMAT		"Invalid output format"
#define	MSG_ERROR_INVALID_ITEMS_FILE_PATH	"Invalid items file path"
#define	MSG_ERROR_INVALID_LIST_FILE_PATH	"Invalid list file path"
#define	MSG_ERROR_INVALID_OUTPUT_FILE_PATH	"Invalid output file path"
#define	MSG_ERROR_INVENTORY_FILE_PATH		"Invalid output inventory file path"
#define MSG_ERROR_INVALID_HEADER_FILE_PATH	"Invalid header file path"
#define MSG_ERROR_INVALID_FOOTER_FILE_PATH	"Invalid footer file path"
#define	MSG_ERROR_UNKNOWN_PRODUCT		"Non-existent product"
#define	MSG_ERROR_NO_MEMORY			"Out of memory"
#define	MSG_ERROR_LIST_FILE_CLOSE		"Incorrect List file close"
#define	MSG_ERROR_ITEMS_FILE_CLOSE		"Incorrect Items file close"
#define MSG_ERROR_OUTPUT_FILE_CLOSE		"Incorrect output file close"
#define MSG_ERROR_HEADER_FILE_CLOSE		"Incorrect Header file close"
#define MSG_ERROR_FOOTER_FILE_CLOSE		"Incorrect Footer file close"
#define MSG_ERROR_INVENTORY_FILE_CLOSE "Incorrect Inventory file close"
#define	MSG_OK					"OK"


